#!/bin/bash
export NFVO_IP=$(unit-get public-address)
export NFVO_PORT=8080
export NFVO_API_VERSION=1
export NFVO_USERNAME=admin
export NFVO_PASSWORD=openbaton
export NFVO_PROJECT_ID=""
export NFVO_SSL_ENABLED=no
# http://stackoverflow.com/a/24387746 for uuid-regex
export NFVO_PROJECT_ID=$(openbaton Project-findAll|grep -oP '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}')

POP_FILE=$JUJU_CHARM_DIR/hooks/pop.json
KEYSTONE_API=$(relation-get api_version)
KEYSTONE_IP=$(relation-get credentials_host)
KEYSTONE_PORT=$(relation-get credentials_port)
KEYSTONE_PROJECT=$(relation-get credentials_project)
KEYSTONE_USERNAME=$(relation-get credentials_username)
KEYSTONE_PASSWORD=$(relation-get credentials_password)

if [ ! -z ${KEYSTONE_API} ]; then
	sed -i "s/localhost/$KEYSTONE_IP/" $POP_FILE
	sed -i "s/PORT/$KEYSTONE_PORT/" $POP_FILE
	sed -i "s/TENANT/$KEYSTONE_PROJECT/" $POP_FILE
	sed -i "s/USER/$KEYSTONE_USERNAME/" $POP_FILE
	sed -i "s/PASSWORD/$KEYSTONE_PASSWORD/" $POP_FILE
fi

openbaton VimInstance-create $POP_FILE
