#!/bin/bash
export NFVO_IP=$(unit-get public-address)
export NFVO_PORT=8080
export NFVO_API_VERSION=1
export NFVO_USERNAME=admin
export NFVO_PASSWORD=openbaton
export NFVO_PROJECT_ID=""
export NFVO_SSL_ENABLED=no
# http://stackoverflow.com/a/24387746 for uuid-regex
export NFVO_PROJECT_ID=$(openbaton Project-findAll|grep -oP '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}')

KEYSTONE_IP=$(relation-get -r $JUJU_RELATION_ID private-address)
VIM_IDS=$(openbaton VimInstance-findAll|grep -oP '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}')

for VIM in $VIM_IDS; do
	openbaton VimInstance-findById $VIM|grep -q $KEYSTONE_IP && openbaton VimInstance-delete $VIM
done
