#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

CONFIG_LOCATION=/tmp/bootstrap_config_file

# get config file and insert config.yaml options as well as default configuration
curl -o $CONFIG_LOCATION "http://get.openbaton.org/bootstrap-config-file"
# set brokerIp to a reachable public ip
sed -i "s/rabbitmq_broker_ip=localhost/rabbitmq_broker_ip=$(unit-get public-address)/" $CONFIG_LOCATION
# overwrite monitoring ip if explicitly set
if [ "$(config-get --format json monitoring_ip)" != "localhost" ] ; then
    juju-log -l "INFO" Monitoring IP set
    sed -i "s/zabbix_server_ip=/zabbix_server_ip=/$(config-get monitoring_ip)/" $CONFIG_LOCATION 
fi
# enable autoscaling-engine, fault management ant network slicing engine
if [ "$(config-get --format json fms)" = "true" ] ; then
    juju-log -l "INFO" FMS enabled
    sed -i "s/openbaton_fms=no/openbaton_fms=yes/" $CONFIG_LOCATION
fi
if [ "$(config-get --format json ase)" = "true" ] ; then
    juju-log -l "INFO" ASE enabled
    sed -i "s/openbaton_ase=no/openbaton_ase=yes/" $CONFIG_LOCATION
fi
if [ "$(config-get --format json nse)" = "true" ] ; then
    juju-log -l "INFO" NSE enabled
    sed -i "s/openbaton_nse=no/openbaton_nse=yes/" $CONFIG_LOCATION
fi
if [ "$(config-get --format json cli)" = "true" ] ; then
    juju-log -l "INFO" CLI enabled
    sed -i "s/openbaton_cli=no/openbaton_cli=yes/" $CONFIG_LOCATION
    # apt-get install python-pip
    # pip install openbaton-cli
fi
# launch the bootstrap script
sh <(curl -s http://get.openbaton.org/bootstrap) "$(config-get branch)" -configFile=$CONFIG_LOCATION

service openbaton-nfvo stop
service openbaton-vnfm-generic stop
service openbaton-ase stop
service openbaton-plugin-monitoring-zabbix stop
service openbaton-fms stop
service openbaton-nse stop

open-port 8080
open-port 5672
open-port 15672
